### ISSUE TITLE
It doesn't play music after joining vc.

### ISSUE THREAD

**Issue by Rishit-Gupta999** [lohanjs/cassette#2]
It says no ffmpeg provided, I have added `ffmpeg.exe` in repository too.

**Comment by lohanjs** [comment]
Depending on where you're hosting the bot, the FFMPEG library has to be on the system path.

**Comment by Rishit-Gupta999** [comment]
Sorry I am re-opening this, I was hosting on [heroku](https://heroku.com/) where I have to provide the ffmpeg there?
